version: "2"

services:
  storage:
    image: openzipkin/zipkin-mysql
    container_name: zipkin-playground-mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-playground-zipkin
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-playground-mysql
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    ports:
      - 9411:9411
    depends_on:
      - storage

  dependencies:
    image: openzipkin/zipkin-dependencies
    container_name: zipkin-playground-dependencies
    entrypoint: crond -f
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-playground-mysql
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    depends_on:
      - storage
